connect/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('gallery.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

gallery/urls.py
from django.urls import path
from .views import (
    MainView,
    ContactView,
    ImageCreateView,
    ImageListView
)

app_name = 'gallery'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('contacts/', ContactView.as_view(), name='contacts'),
    path('load/', ImageCreateView.as_view(), name='load'),
    path('gallery/', ImageListView.as_view(), name='gallery'),
]

extra/models.py
from django.db import models


class DownCode(models.Model):
    '''Код перед </body>'''

    class Meta():
        verbose_name = 'Дополнительный код'
        verbose_name_plural = 'Дополнительный код'

    title = models.CharField('Название', max_length=300)
    code = models.TextField('Код',
                            help_text='Код для вставки на каждую страницу сайта (код счетчиков, метрик и тд). Располагается перед </body>. Будте осторожны! Этот код вставляется как есть - он может повредить работоспособности сайта!')
    approved = models.BooleanField('Включить\Выключить', default=True)

    def __str__(self):
        return self.title


class MetaTag(models.Model):
    '''Мета теги для head'''

    class Meta():
        verbose_name = 'Мета тег для head'
        verbose_name_plural = "Мета теги для head"

    name = models.CharField(
        'name/property',
        max_length=100,
        help_text='Пример содержания: name="keywords"'
    )
    content = models.TextField('Content', )
    approved = models.BooleanField('Включить\Выключить', default=True)

    def __str__(self):
        return self.name

gallery/models.py
from django.db import models
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFit


class Image(models.Model):
    '''Изображения'''

    description = models.TextField('Комментарий для изображения', blank=True)
    img = models.ImageField('Изображение', upload_to='images')
    img_small = ImageSpecField(
        source='img',
        processors=[ResizeToFit(width=300, height=1000)],
        format='JPEG',
        options={'quality': 80}
    )
    img_thumbnail = ImageSpecField(
        source='img',
        processors=[ResizeToFit(width=150, height=500)],
        format='JPEG',
        options={'quality': 100}
    )
    created = models.DateTimeField('Время создания', auto_now_add=True)
    approved = models.BooleanField('Включить\Выключить', default=True)

    class Meta():
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'
        ordering = ['-created']

    def __str__(self):
        return str(self.id)

gallery/forms.py
from django import forms
from django.forms import Textarea, FileInput
from .models import Image


class ImageForm(forms.ModelForm):
    '''Форма добавления изображения'''

    class Meta:
        model = Image
        fields = ('description', 'img')
        widgets = {
            'description': Textarea(attrs={'class': 'form-input'}),
            'img': FileInput(attrs={'class': 'form-input'}),
        }

extra/views.py
from django.shortcuts import render

# Create your views here.

gallery/views.py
from django.urls import reverse_lazy
from .forms import ImageForm
from .models import Image
from django.views.generic import (
    TemplateView,
    CreateView,
    ListView
)


class MainView(TemplateView):
    '''Тестовое задание'''

    template_name = 'gallery/index.html'

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        context['page_title'] = self.__doc__
        return context


class ContactView(TemplateView):
    '''Мои контакты'''

    template_name = 'gallery/contacts.html'

    def get_context_data(self, **kwargs):
        context = super(ContactView, self).get_context_data(**kwargs)
        context['page_title'] = self.__doc__
        return context


class ImageCreateView(CreateView):
    '''Форма загрузки изображений'''

    template_name = 'gallery/form.html'
    model = Image
    form_class = ImageForm

    def get_context_data(self, **kwargs):
        context = super(ImageCreateView, self).get_context_data(**kwargs)
        context['page_title'] = self.__doc__
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('gallery:gallery')


class ImageListView(ListView):
    '''Галерея изображений'''

    model = Image
    template_name = 'gallery/list.html'

    def get_context_data(self, **kwargs):
        context = super(ImageListView, self).get_context_data(**kwargs)
        context['page_title'] = self.__doc__
        return context

    def get_queryset(self):
        return Image.objects.filter(approved=True)

templates/base.html
{% load staticfiles %}
{% load compress %}
<!DOCTYPE HTML>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    {% block meta %}
        {% for meta_tag in meta_tags %}
            <meta {{ meta_tag.name|safe }} content="{{ meta_tag.content }}">
        {% endfor %}
    {% endblock %}
    <title>{% block title %}Test work{% endblock %}</title>
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">
    {% compress css %}
        <link rel="stylesheet" href="{% static 'gallery/css/style.css' %}">
        {% block styles %}{# Дополнительные стили, подключаемые на страницах #}{% endblock %}
    {% endcompress %}
</head>
<body>
{% include 'header.html' %}
<section class="main_section">
    {% block content %}{# Основной контент сайта #}{% endblock %}
</section>
{% compress js %}
    {% block scripts %}{# Дополнительные скрипты, подключаемые на страницах #}{% endblock %}
{% endcompress %}
{% for item in codes %}
    {% autoescape off %}
        {{ item.code }}
    {% endautoescape %}
{% endfor %}
</body>
</html>

templates/gallery/contacts.html
{% extends 'base.html' %}

{% block title %}
    {{ page_title }} - {{ block.super }}
{% endblock %}

{% block content %}

    <h3 class="text-center">{{ page_title }}</h3>
    <div class="divider"></div>
    <div class="clear20"></div>

    {# TODO: контакты сделать ссылками #}
    <p>skype: <b><a href="skype:birukov.alex">birukov.alex</a></b></p>
    <p>telegram: <b><a href="https://t.me/birukov_alex">@birukov_alex</a></b></p>
    <p>phone: <b><a href="tel:+79045904350">+7(904)590-43-50</a></b></p>

{% endblock content %}

templates/gallery/form.html
{% extends 'base.html' %}

{% block title %}
    {{ page_title }} - {{ block.super }}
{% endblock %}

{% block content %}

    <h3 class="text-center">{{ page_title }}</h3>
    <div class="clear10"></div>
    <form action="{% url 'gallery:load' %}" method="post" id="load_form" class="col-8 col-mx-auto"
          enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <div class="clear20"></div>
        <button class="btn btn-primary">Сохранить</button>
    </form>

{% endblock content %}

templates/gallery/index.html
{% extends 'base.html' %}

{% block title %}
    {{ page_title }} - {{ block.super }}
{% endblock %}

{% block content %}

    <h1 class="text-center">{{ page_title }}</h1>

    <blockquote class="bg-gray">
        <p>В качестве тестового задания предлагаем реализовать следующий проект:</p>
        <ul>
            <li>Веб сайт из 2х страниц. Форма, на которой есть возможность выбрать файл и написать комментарий к нему.
                Выбирать и загружать можно только картинки (jpg и т.д.)
            </li>
            <li>Страница, на которой отображаются уже загруженные картинки и комментарии в виде мозаики (плиток,
                превью), при клике открывается полноразмерная картинка.
            </li>
            <li>Хотелось бы, что бы это было реализовано на django или flask</li>
            <li>Проект выложить на приватный репо gitbub или bitbucket (аккаунт в обеих системах lexapi)</li>
        </ul>
    </blockquote>

    <div class="clear20"></div>
    <div class="divider text-center" data-content="REQUIREMETS"></div>
    <ul>
        <li><b>Python</b>
            <ul>
                <li>
                    <a href="https://www.djangoproject.com/" target="_blank">Django==2.0.3</a></li>
                <li>
                    <a href="https://github.com/matthewwithanm/django-imagekit"
                       target="_blank">django-imagekit==4.0.2</a>
                </li>
            </ul>
        </li>
        <li><b>Java Script</b>
            <ul>
                <li>Jquery</li>
                <li>
                    <a href="https://appelsiini.net/projects/lazyload/" target="_blank">Lazyload</a>
                </li>
                <li>
                    <a href="http://fancyapps.com/fancybox/3/" target="_blank">Fancybox</a>
                </li>
            </ul>
        </li>
        <li><b>CSS</b>
            <ul>
                <li>
                    <a href="https://picturepan2.github.io/spectre/" target="_blank">Spectre</a>
                </li>
            </ul>
        </li>
    </ul>

{% endblock content %}

templates/gallery/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'gallery/css/jquery.fancybox.min.css' %}"/>
{% endblock styles %}
{% block scripts %}
    <script src="{% static 'gallery/js/jquery-3.2.0.min.js' %}"></script>
    <script src="{% static 'gallery/js/lazyload.min.js' %}"></script>
    <script src="{% static 'gallery/js/jquery.fancybox.min.js' %}"></script>
    <script>
        lazyload();
    </script>
{% endblock %}

{% block title %}
    {{ page_title }} - {{ block.super }}
{% endblock %}

{% block content %}

    <h3 class="text-center">{{ page_title }}</h3>

    <div id="gal_container">
        {% for image in image_list %}
            <div class="card">
                <a href="{{ image.img.url }}"
                   class="card-image"
                   data-fancybox="gal"
                   data-caption="{{ image.description }}">
                    <img src="" class="img-responsive lazyload" data-src="{{ image.img_small.url }}">
                </a>
                {% if image.description %}
                    <div class="card-body">{{ image.description }}</div>
                {% endif %}
            </div>
        {% endfor %}
    </div>

{% endblock content %}

templates/header.html
<header class="bg-secondary">
    <div class="navbar">
        <section class="navbar-section">
            <a href="{% url 'gallery:main' %}" class="btn btn-link">Тестовое задание</a>
            <a href="{% url 'gallery:contacts' %}" class="btn btn-link">Контакты</a>
        </section>
        <section class="navbar-section">
            <a href="{% url 'gallery:load' %}" class="btn btn-link"><span class="text-error">Форма загрузки изображений</span></a>
            <a href="{% url 'gallery:gallery' %}" class="btn btn-link"><span class="text-error">Галерея изображений</span></a>
        </section>
    </div>
</header>